# Phase 1.1 — Tensor Basics

**Create, inspect, reshape** — the building blocks of everything in PyTorch.

Run cells in order. Modify values and re-run to explore.

In [1]:
import torch

torch.manual_seed(42)  # reproducible demos

## Creating tensors

| Function | Use case |
|----------|----------|
| `torch.tensor([...])` | From Python list (copies data) |
| `torch.zeros` / `ones` / `full` | Fill with constant |
| `torch.arange` / `linspace` | Sequences |
| `torch.randn` | Random from N(0,1) |
| `torch.eye(n)` | Identity matrix |

In [2]:
a = torch.tensor([1, 2, 3])           # 1D
b = torch.zeros(2, 3)                 # 2×3 filled with 0
c = torch.randn(2, 3)                   # random
d = torch.arange(0, 10, 2)            # [0, 2, 4, 6, 8]
e = torch.eye(3)                      # 3×3 identity

for name, t in zip("abcde", [a, b, c, d, e]):
    print(f"{name}: shape={tuple(t.shape)}, dtype={t.dtype}, device={t.device}")

a: shape=(3,), dtype=torch.int64, device=cpu
b: shape=(2, 3), dtype=torch.float32, device=cpu
c: shape=(2, 3), dtype=torch.float32, device=cpu
d: shape=(5,), dtype=torch.int64, device=cpu
e: shape=(3, 3), dtype=torch.float32, device=cpu


## Shape, rank, numel

- **shape** — size per dimension `(rows, cols)`
- **ndim** (rank) — number of dimensions
- **numel** — total elements = product of shape

In [3]:
t = torch.randn(2, 3, 4)  # 2 batches, 3×4 each

print(f"shape  : {tuple(t.shape)}")
print(f"ndim   : {t.ndim}")
print(f"numel  : {t.numel()}  (= 2×3×4 = {2*3*4})")
print(f"size(1): {t.size(1)}  # length of dim 1")

shape  : (2, 3, 4)
ndim   : 3
numel  : 24  (= 2×3×4 = 24)
size(1): 3  # length of dim 1


## Reshape (same data, new view of dimensions)

`.reshape()` and `.view()` change shape without copying (usually).  
**Rule:** total elements must stay the same.

```python
x.reshape(2, -1)   # -1 = infer this dim
```

In [4]:
x = torch.arange(12)
print(f"original: {tuple(x.shape)} → {x.tolist()}")

row = x.reshape(3, 4)
col = x.reshape(4, 3)
flat = row.reshape(-1)  # back to 1D

print(f"3×4:\n{row}")
print(f"flatten: {flat.tolist()}")

original: (12,) → [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
3×4:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
flatten: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


### 🧪 Quiz — before running the next cell

`torch.arange(6).reshape(2, -1)` — what will the shape be?

In [5]:
t = torch.arange(6).reshape(2, -1)
print(f"shape: {tuple(t.shape)}")
print(t)

shape: (2, 3)
tensor([[0, 1, 2],
        [3, 4, 5]])


## ✏️ Exercise

Create a tensor `m` with shape **(4, 4)** containing the numbers **0 through 15** (in order), using `torch.arange` + reshape.

Then create `row0` = first row of `m` (shape `(4,)`).

In [17]:
# YOUR CODE
m = torch.arange(16).reshape(4, 4)
row0 = m.reshape(4, -1)[0]

print(m)
print(f"\nrow0: {row0}, shape={tuple(row0.shape)}")

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

row0: tensor([0, 1, 2, 3]), shape=(4,)


In [18]:
assert m.shape == (4, 4)
assert torch.equal(m, torch.arange(16).reshape(4, 4))
assert row0.shape == (4,)
assert torch.equal(row0, m[0])
print("✓ Phase 1.1 passed!")

✓ Phase 1.1 passed!
